### ISSUE TITLE
Items Request

### ISSUE THREAD

**Issue by allamiro** [LibraryofVA/omeka-themes#1]
There is an issue when creating item it wont display and it complains about item type conext dont exist using DBVA theme on omeka

**Comment by jasonroma** [comment]
What type of items are you creating? The DBVA theme was built to be used along with items of the type Lesson Plan and from the error you mention I wonder if that might be the problem. If there is an exact error or screen shot that would be helpful in narrowing down the cause as well.

**Comment by jasonroma** [comment]
Assuming problem resolved.
